language: perl

dist: xenial

sudo: required

install:
    - sudo apt-get -y install tklib libtk-img tix tk-table
    - xvfb-run -a cpanm --verbose --notest --installdeps .

script:
    - xvfb-run -a perl Makefile.PL
    - xvfb-run -a make test

perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
