language: perl

dist: xenial

sudo: required

install:
# TkTable in recent Ubuntu/Debian currently causes
# invalid free() on program exit when used from Perl/Tcl.pm.
# See https://www.mail-archive.com/tcltk@perl.org/msg00817.html
#   - sudo apt-get -y install bwidget tklib libtk-img tix tk-table
    - sudo apt-get -y install bwidget tklib libtk-img tix
# Install Tcl.pm without stubs for potentially better debugging
# (also requires specifying where tcl.h is)
    - cpanm --verbose --notest Tcl --configure-args="--nousestubs -INC=-I/usr/include/tcl8.6"
    - xvfb-run -a cpanm --verbose --notest --installdeps .

script:
    - xvfb-run -a perl Makefile.PL
    - xvfb-run -a make test

perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
